###
GET http://localhost:5000/profesores

###
GET http://localhost:5000/profesores/2

###
POST http://localhost:5000/profesores
content-type: application/json

{
    "nombre": "jujujuj",
    "apellido": "jijij"
}
###
PUT http://localhost:5000/profesores/5
content-type: application/json

{
    "nombre": "gol",
    "apellido": "messi"
}

###
DELETE http://localhost:5000/profesores/2

